// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import GeolocationController from "./geolocation_controller";
application.register("geolocation", GeolocationController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import Leaflet__PostsCreateController from "./leaflet/posts_create_controller";
application.register("leaflet--posts-create", Leaflet__PostsCreateController);

import Leaflet__PostsIndexController from "./leaflet/posts_index_controller";
application.register("leaflet--posts-index", Leaflet__PostsIndexController);

import Leaflet__PostsShowController from "./leaflet/posts_show_controller";
application.register("leaflet--posts-show", Leaflet__PostsShowController);
