// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LeafletPostsIndexController from "./leaflet/leaflet_posts_index_controller"
application.register("leaflet_posts_index", LeafletPostsIndexController)

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LeafletPostsCreateController from "./leaflet/leaflet_posts_create_controller"
application.register("leaflet_posts_create", LeafletPostsCreateController)
